version: "3.8"

services:
  traefik:
    image: "traefik:2.9.9"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs"
      - "./config.yml:/etc/traefik/dynamic_conf/conf.yml:ro"
    networks:
      - proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.traefik.loadbalancer.server.port=80"
        - "traefik.http.services.traefik.loadbalancer.server.port=443"
        - "traefik.http.middlewares.httpsonly.redirectscheme.scheme=https"
        - "traefik.http.middlewares.httpsonly.redirectscheme.permanent=true"
        - "traefik.http.routers.httpsonly.rule=HostRegexp(`{any:.*}`)"
        - "traefik.http.routers.httpsonly.middlewares=httpsonly"
        - "traefik.http.routers.dashboard.rule=Host(`dashboard.traefik.me`)"
        - "traefik.http.routers.dashboard.service=dashboard@internal"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.api.rule=Host(`dashboard.traefik.me`) && PathPrefix(`/api`)"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.tls=true"

networks:
  proxy:
    name: proxy
    driver: overlay
    attachable: true
    ipam: 
      config:
        - subnet: "10.10.28.0/24"
          gateway: "10.10.28.1"