version: "3.8"

services:
  registry:
    container_name: registry
    image: registry:2.8.1
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - "registry-data:/data"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"
      - "traefik.http.routers.registry.rule=Host(`registry.traefik.me`)"
      - "traefik.http.routers.registry.tls=true"
      - "traefik.http.routers.registry.entrypoints=websecure"

networks:
  proxy:
    external: true

volumes:
  registry-data:
    name: registry-data