version: "3.8"

services:
  whoami:
    image: nginx:latest
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.nginx.entrypoints=websecure
        - traefik.http.routers.nginx.rule=Host(`nginx.traefik.me`)
        - traefik.http.routers.nginx.service=nginx
        - traefik.http.routers.nginx.tls=true
        - traefik.http.services.nginx.loadbalancer.server.port=80
    networks:
      - proxy

networks:
  proxy:
    external: true