version: "3.8"

services:
  whoami:
    container_name: whoami
    image: traefik/whoami:latest
    command:
      - "--port=8080"
      - "--name=whoami-portainer"
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.rule=Host(`whoami.traefik.me`)
      - traefik.http.routers.whoami.service=whoami
      - traefik.http.routers.whoami.tls=true
      - traefik.http.services.whoami.loadbalancer.server.port=8080
    networks:
      - proxy

networks:
  proxy:
    external: true