version: "3.8"

services:
  whoami:
    image: traefik/whoami:latest
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.whoami.entrypoints=websecure
        - traefik.http.routers.whoami.rule=Host(`whoami.traefik.me`)
        - traefik.http.routers.whoami.service=whoami
        - traefik.http.routers.whoami.tls=true
        - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - proxy

networks:
  proxy:
    external: true